### ISSUE TITLE
No compatible versions available (imagemagick )

### ISSUE THREAD

**Issue by walter-weinmann** [mangalakader/asdf-imagemagick#6]
Currently the result after:

```
asdf plugin add imagemagick
asdf list all imagemagick
```

**Comment by mangalakader** [comment]
@walter-weinmann 

$ asdf list-all imagemagick 
7.0.10-54
7.0.10-55
7.0.10-56
7.0.10-57
7.0.10-58
7.0.10-59
7.0.10-60
7.0.10-61
7.0.10-62
7.0.11-0
7.0.11-1
7.0.11-2
...
...

This is what I'm getting!

Please provide further details about your OS version information and asdf informations too.

**Comment by walter-weinmann** [comment]
This happens when `curl` is missing.
